export const LeadData = [
    {
        id: 'Lead',
        name: 'Sahil Ambure',
        profile: 'SahilAmbure.jpg',
        linkedin: 'https://www.linkedin.com/in/sahil-ambure/',
    }
];


export const CoreTeamData = [
    {
        id: 'Lead1',
        name: 'Sahil Bodke',
        profile: 'SahilBodke.jpg',
        position: 'Co-Lead GDSC',
        department: 'Co-Lead',
        gender: 'He',
        linkedin: 'http://www.linkedin.com/in/sahil-bodke-45570a251',
    },
    {
        id: 'Lead2',
        name: 'Himanshu Bhoir',
        profile: 'HimanshuBhoir.jpg',
        position: 'Project Head Web',
        department: 'Web',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in',
    },
    {
        id: 'Lead3',
        name: 'Tanmay Bhole',
        profile: 'male.png',
        position: 'Project Head App',
        department: 'App',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/tanmay-bhole-0453a7262/',
    },
    {
        id: 'Lead4',
        name: 'Ritesh Mishra',
        profile: 'male.png',
        position: 'Project Head AI/ML',
        department: 'AI/ML',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: 'Lead5',
        name: 'Shruti Kulkarni',
        profile: 'female.png',
        position: 'Treasurer',
        department: 'Treasurer',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: 'Lead6',
        name: 'Vibhanshu Dubey',
        profile: 'VibhanshuDubey.jpg',
        position: 'Marketing Head',
        department: 'Marketing',
        gender: 'He',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: 'Lead7',
        name: 'Kunal More',
        profile: 'male.png',
        position: 'Publicity Head',
        department: 'Publicity',
        gender: 'He',
        linkedin: 'https://www.linkedin.com',
    },
    {
        id: 'Lead8',
        name: 'Saachi Gadling',
        profile: 'SaachiGadling.png',
        position: 'Creative Head',
        department: 'Creative',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    }, 
    {
        id: 'Lead9',
        name: 'Anuska Kadam',
        profile: 'female.png',
        position: 'Media Head',
        department: 'Media',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
];

export const Teams = [
    {
        id: '1',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        linkedin: 'https://www.linkedin.com/in/omkar-mandave-598708260',
        gender: 'She',
    },
    {
        id: '2',
        name: 'Omkar Mandave',
        department: 'App',
        position: 'Co-head',
        profile: 'OmkarMandave.jpg',
        gender: 'Hee',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '3',
        name: 'Aryan Nipane',
        department: 'AI/ML',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/',
    },
    {
        id: '4',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '5',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '6',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '7',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '8',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '9',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '10',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '1',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
        gender: 'She',
    },
    {
        id: '2',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '3',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '4',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '5',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '6',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '7',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '8',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '9',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '10',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '1',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
        gender: 'She',
    },
    {
        id: '2',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '3',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '4',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '5',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '6',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '7',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '8',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '9',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '10',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '1',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
        gender: 'She',
    },
    {
        id: '2',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '3',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '4',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '5',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '6',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '7',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '8',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    {
        id: '9',
        name: 'Aryan Nipane',
        department: 'Web',
        position: 'Co-head',
        profile: 'HimanshuBhoir.jpg',
        gender: 'She',
        linkedin: 'https://www.linkedin.com/in/himanshu-bhoir-34a9a01b9/',
    },
    
];